export const FileNames = [
  "Networking & Content Delivery/Amazon-CloudFront_Edge-Location_light-bg.svg",
  "Networking & Content Delivery/Amazon-VPC_Router_light-bg.svg",
  "Networking & Content Delivery/Amazon-VPC_NAT-Gateway_light-bg.svg",
  "Networking & Content Delivery/AWS-Direct-Connect_light-bg.svg",
  "Networking & Content Delivery/Amazon-VPC_Network-Access-Control-List_light-bg.svg",
  "Networking & Content Delivery/Amazon-VPC_Elastic-Network-Interface_light-bg.svg",
  "Networking & Content Delivery/Amazon-API-Gateway_Endpoint_light-bg.svg",
  "Networking & Content Delivery/AWS-Cloud-Map_light-bg.svg",
  "Networking & Content Delivery/Amazon-API-Gateway_light-bg.svg",
  "Networking & Content Delivery/Amazon-VPC_Elastic-Network-Adapter_light-bg.svg",
  "Networking & Content Delivery/Amazon-CloudFront_Download-Distribution_light-bg.svg",
  "Networking & Content Delivery/Amazon-Route-53_Hosted-Zone_light-bg.svg",
  "Networking & Content Delivery/AWS-App-Mesh_light-bg.svg",
  "Networking & Content Delivery/Amazon-VPC-Traffic-Mirroring_light-bg.svg",
  "Networking & Content Delivery/Amazon-VPC_Endpoints_light-bg.svg",
  "Networking & Content Delivery/Elastic-Load-Balancing_light-bg.svg",
  "Networking & Content Delivery/AWS-Client-VPN_light-bg.svg",
  "Networking & Content Delivery/Amazon-Route-53_Route-Table_light-bg.svg",
  "Networking & Content Delivery/Amazon-VPC_light-bg.svg",
  "Networking & Content Delivery/Elastic-Load-Balancing_Classic-load-balancer_light-bg.svg",
  "Networking & Content Delivery/AWS-Global-Accelerator_light-bg.svg",
  "Networking & Content Delivery/Amazon-VPC_VPN-Gateway_light-bg.svg",
  "Networking & Content Delivery/Elastic-Load-Balancing-ELB_Network-load-balancer_light-bg.svg",
  "Networking & Content Delivery/Elastic-Load-Balancing-ELB_Application-load-balancer_light-bg.svg",
  "Networking & Content Delivery/Amazon-VPC_VPN-Connection_light-bg.svg",
  "Networking & Content Delivery/Amazon-VPC_Internet-Gateway_light-bg.svg",
  "Networking & Content Delivery/Amazon-CloudFront_Streaming-Distribution_light-bg.svg",
  "Networking & Content Delivery/AWS-PrivateLink_light-bg.svg",
  "Networking & Content Delivery/Amazon-VPC_Flow-Logs_light-bg.svg",
  "Networking & Content Delivery/Amazon-CloudFront_light-bg.svg",
  "Networking & Content Delivery/Amazon-VPC_Customer-Gateway_light-bg.svg",
  "Networking & Content Delivery/Amazon-Route-53_light-bg.svg",
  "Networking & Content Delivery/Networking-and-Content-Delivery_light-bg.svg",
  "Networking & Content Delivery/AWS-Transit-Gateway_light-bg.svg",
  "Networking & Content Delivery/Amazon-VPC_Peering_light-bg.svg",
  "Networking & Content Delivery/AWS-Site-to-Site-VPN_light-bg.svg",
  "Game Tech/Game-Tech_light-bg.svg",
  "Game Tech/Amazon-GameLift_light-bg.svg",
  "End User Computing/Amazon-Workspaces_light-bg.svg",
  "End User Computing/Amazon-Appstream-2.0_light-bg.svg",
  "End User Computing/End-User-Computing_light-bg.svg",
  "End User Computing/Amazon-WorkLink_light-bg.svg",
  "End User Computing/Amazon-WorkDocs_light-bg.svg",
  "Application Integration/Amazon-Simple-Notification-Service-SNS_HTTP-Notification_light-bg.svg",
  "Application Integration/Amazon-EventBridge_Saas-Partner-event-bus_resource-icon_light-bg.svg",
  "Application Integration/Application-Integration_light-bg.svg",
  "Application Integration/Amazon-Simple-Queue-Service-SQS_light-bg.svg",
  "Application Integration/Amazon-AppSync_light-bg.svg",
  "Application Integration/Application-Integration_Event_Resource_light-bg.svg",
  "Application Integration/Amazon-Simple-Notification-Service-SNS_Email-Notification_light-bg.svg",
  "Application Integration/Amazon-EventBridge_Custom-event-bus_resource-icon_light-bg.svg",
  "Application Integration/AWS-Express-Workflows_light-bg.svg",
  "Application Integration/AWS-Console-Mobile-Application_light-bg.svg",
  "Application Integration/Amazon-Simple-Notification-Service-SNS_Topic_light-bg.svg",
  "Application Integration/Amazon-Simple-Queue-Service-SQS_Queue_light-bg.svg",
  "Application Integration/AWS-Step-Functions_light-bg.svg",
  "Application Integration/Amazon-EventBridge_Default-event-bus_resource-icon_light-bg.svg",
  "Application Integration/Amazon-MQ_light-bg.svg",
  "Application Integration/Amazon-Simple-Notification-Service-SNS_light-bg.svg",
  "Application Integration/Amazon-EventBridge_light-bg.svg",
  "Application Integration/Amazon-Simple-Queue-Service-SQS_Message_light-bg.svg",
  "Mobile/AWS-AppSync_light-bg.svg",
  "Mobile/Amazon-Pinpoint_light-bg.svg",
  "Mobile/AWS-Device-Farm_light-bg.svg",
  "Mobile/Amazon-API-Gateway_Endpoint_light-bg.svg",
  "Mobile/Amazon-API-Gateway_light-bg.svg",
  "Mobile/Mobile_light-bg.svg",
  "Mobile/AWS-Amplify_light-bg.svg",
  "Compute/Amazon-Elastic-Kubernetes-Service_light-bg.svg",
  "Compute/AWS-Serverless-Application-Repository_light-bg.svg",
  "Compute/AWS-Compute-Optimizer_light-bg.svg",
  "Compute/Amazon-EC2_Rescue_light-bg.svg",
  "Compute/VMware-Cloud-On-AWS_light-bg.svg",
  "Compute/AWS-Lambda_Lambda-Function_light-bg.svg",
  "Compute/Amazon-EC2-Auto-Scaling_light-bg.svg",
  "Compute/EC2-Image-Builder_light-bg.svg",
  "Compute/AWS-Wavelength_light-bg.svg",
  "Compute/AWS-Thinkbox-Draft_light-bg.svg",
  "Compute/AWS-Lambda_light-bg.svg",
  "Compute/Amazon-EC2_AMI_light-bg.svg",
  "Compute/Amazon-Application-Auto-Scaling_light-bg.svg",
  "Compute/Parallel-Cluster_light-bg.svg",
  "Compute/AWS-Thinkbox-Deadline_light-bg.svg",
  "Compute/AWS-Elastic-Beanstalk_light-bg.svg",
  "Compute/Amazon-EC2_Elastic-IP-Address_light-bg.svg",
  "Compute/AWS-Local-Zones_light-bg.svg",
  "Compute/AWS-Outposts_light-bg.svg",
  "Compute/AWS-Thinkbox-Krakatoa_light-bg.svg",
  "Compute/Compute_light-bg.svg",
  "Compute/AWS-Batch_light-bg.svg",
  "Compute/AWS-Thinkbox-Sequoia_light-bg.svg",
  "Compute/AWS-Thinkbox-Stoke_light-bg.svg",
  "Compute/Bottlerocket_light-bg.svg",
  "Compute/Amazon-Elastic-Container-Service_Container3_light-bg.svg",
  "Compute/Amazon-Elastic-Container-Service_Container2_light-bg.svg",
  "Compute/AWS-Fargate_light-bg.svg",
  "Compute/Amazon-Elastic-Container-Service_Task_light-bg.svg",
  "Compute/AWS-Elastic-Beanstalk_Application_light-bg.svg",
  "Compute/Amazon-Lightsail_light-bg.svg",
  "Compute/AWS-Elastic-Beanstalk_Deployment_light-bg.svg",
  "Compute/Amazon-Elastic-Container-Service_light-bg.svg",
  "Compute/Amazon-Elastic-Container-Service_Service_light-bg.svg",
  "Compute/AWS-Thinkbox-Frost_light-bg.svg",
  "Compute/Amazon-Elastic-Container-Service_Container1_light-bg.svg",
  "Compute/Amazon-EC2_Auto-Scaling_light-bg.svg",
  "Compute/Amazon-EC2_light-bg.svg",
  "Compute/Amazon-EC2-Container-Registry_Registry_light-bg.svg",
  "Compute/Amazon-EC2-Container-Registry_light-bg.svg",
  "Compute/Amazon-EC2-Container-Registry_Image_light-bg.svg",
  "Compute/AWS-Thinkbox_XMesh_light-bg.svg",
  "Migration & Transfer/AWS-Snowball_light-bg.svg",
  "Migration & Transfer/AWS-Transfer-for-FTP_Resource-Icon_light-bg.svg",
  "Migration & Transfer/CloudEndure-Migration_light-bg.svg",
  "Migration & Transfer/AWS-Migration-Hub_light-bg.svg",
  "Migration & Transfer/AWS-Database-Migration-Service_light-bg.svg",
  "Migration & Transfer/AWS-Snowmobile_light-bg.svg",
  "Migration & Transfer/Migration-and-Transfer_light-bg.svg",
  "Migration & Transfer/AWS-Application-Discovery-Service_light-bg.svg",
  "Migration & Transfer/AWS-DataSync_light-bg.svg",
  "Migration & Transfer/AWS-Snowball-Edge_light-bg.svg",
  "Migration & Transfer/AWS-DataSync_Agent_light-bg.svg",
  "Migration & Transfer/AWS-Server-Migration-Service_light-bg.svg",
  "Migration & Transfer/AWS-Transfer-Family_light-bg.svg",
  "Migration & Transfer/AWS-Transfer-for-SFTP_Resource-Icon_light-bg.svg",
  "Migration & Transfer/AWS-Transfer-for-FTPS_Resource-Icon_light-bg.svg",
  "Customer Engagement/Amazon-Connect_light-bg.svg",
  "Customer Engagement/Amazon-Pinpoint_light-bg.svg",
  "Customer Engagement/Customer-Engagement_light-bg.svg",
  "Customer Engagement/Amazon-Simple-Email-Service-SES_Email_light-bg.svg",
  "Customer Engagement/Amazon-Simple-Email-Service-SES_light-bg.svg",
  "Management & Governance/AWS-Systems-Manager_Maintenance-Windows_light-bg.svg",
  "Management & Governance/AWS-OpsWorks_light-bg.svg",
  "Management & Governance/AWS-CloudFormation_Stack_light-bg.svg",
  "Management & Governance/AWS-Systems-Manager_State-Manager_light-bg.svg",
  "Management & Governance/AWS-OpsWorks_Deployments_light-bg.svg",
  "Management & Governance/AWS-Well-Architected-Tool_light-bg.svg",
  "Management & Governance/AWS-OpsWorks_Permissions_light-bg.svg",
  "Management & Governance/Amazon-CloudWatch_Alarm_light-bg.svg",
  "Management & Governance/AWS-Organizations_Organizational-unit_light-bg.svg",
  "Management & Governance/AWS-Control-Tower_light-bg.svg",
  "Management & Governance/AWS-CloudFormation_light-bg.svg",
  "Management & Governance/AWS-OpsWorks_Apps_light-bg.svg",
  "Management & Governance/AWS-CloudFormation_Change-Set_light-bg.svg",
  "Management & Governance/AWS-Service-Catalog_light-bg.svg",
  "Management & Governance/AWS-OpsWorks_Layers_light-bg.svg",
  "Management & Governance/Amazon-CloudWatch_Event-Event-Based_light-bg.svg",
  "Management & Governance/Systems-Manager_OpsCenter_light-bg.svg",
  "Management & Governance/Amazon-CloudWatch_light-bg.svg",
  "Management & Governance/AWS-License-Manager_light-bg.svg",
  "Management & Governance/AWS-OpsWorks_Instances_light-bg.svg",
  "Management & Governance/AWS-Trusted-Advisor_Checklist-Security_light-bg.svg",
  "Management & Governance/AWS-CloudFormation_Template_light-bg.svg",
  "Management & Governance/AWS-Systems-Manager_Inventory_light-bg.svg",
  "Management & Governance/AWS-Systems-Manager_Parameter-Store_light-bg.svg",
  "Management & Governance/AWS-Trusted-Advisor_Checklist_light-bg.svg",
  "Management & Governance/AWS-Organizations_light-bg.svg",
  "Management & Governance/AWS-CloudTrail_light-bg.svg",
  "Management & Governance/AWS-OpsWorks_Resources_light-bg.svg",
  "Management & Governance/AWS-OpsWorks_Monitoring_light-bg.svg",
  "Management & Governance/AWS-Systems-Manager_Patch-Manager_light-bg.svg",
  "Management & Governance/AWS-Organizations_Account_light-bg.svg",
  "Management & Governance/AWS-Systems-Manager_Automation_light-bg.svg",
  "Management & Governance/AWS-Managed-Services_light-bg.svg",
  "Management & Governance/AWS-App-Config_light-bg.svg",
  "Management & Governance/AWS-Systems-Manager_Documents_light-bg.svg",
  "Management & Governance/AWS-OpsWorks_Stack2_light-bg.svg",
  "Management & Governance/AWS-Trusted-Advisor_Checklist-Performance_light-bg.svg",
  "Management & Governance/AWS-Trusted-Advisor_light-bg.svg",
  "Management & Governance/Amazon-CloudWatch_Rule_light-bg.svg",
  "Management & Governance/AWS-Systems-Manager_Run-Command_light-bg.svg",
  "Management & Governance/AWS-Personal-Health-Dashboard_light-bg.svg",
  "Management & Governance/Amazon-CloudWatch_Event-Time-Based_light-bg.svg",
  "Management & Governance/AWS-Management-Console_light-bg.svg",
  "Management & Governance/AWS-Systems-Manager_light-bg.svg",
  "Management & Governance/AWS-Config_light-bg.svg",
  "Management & Governance/AWS-Trusted-Advisor_Checklist-Cost_light-bg.svg",
  "Management & Governance/AWS-Command-Line-Interface_light-bg.svg",
  "Management & Governance/AWS-Auto-Scaling_light-bg.svg",
  "Management & Governance/AWS-Trusted-Advisor_Checklist-Fault-Tolerant_light-bg.svg",
  "Management & Governance/Management-and-Governance_light-bg.svg",
  "AR & VR/Amazon-Sumerian_light-bg.svg",
  "AR & VR/AR-VR_light-bg.svg",
  "Analytics/Amazon-EMR_Cluster_light-bg.svg",
  "Analytics/Amazon-Redshift_Dense-storage-node_light-bg.svg",
  "Analytics/Amazon-CloudSearch_Search-documents_light-bg.svg",
  "Analytics/Amazon-Athena_light-bg.svg",
  "Analytics/Amazon-Redshift_Dense-compute-node_light-bg.svg",
  "Analytics/Amazon-EMR_EMR-engine-MapR-M5_light-bg.svg",
  "Analytics/AWS-Lake-Formation_light-bg.svg",
  "Analytics/Amazon-EMR_EMR-engine-MapR-M3_light-bg.svg",
  "Analytics/Amazon-Kinesis-Video-Streams_light-bg.svg",
  "Analytics/Amazon-CloudSearch_light-bg.svg",
  "Analytics/Amazon-Kinesis_light-bg.svg",
  "Analytics/Amazon-Managed-Streaming-for-Kafka_light-bg.svg",
  "Analytics/Amazon-Redshift_light-bg.svg",
  "Analytics/AWS-Data-lake_Resource-icon_light-bg.svg",
  "Analytics/Amazon-Kinesis-Data-Analytics_light-bg.svg",
  "Analytics/Analytics_light-bg.svg",
  "Analytics/Amazon-EMR_light-bg.svg",
  "Analytics/Amazon-Quicksight_light-bg.svg",
  "Analytics/Amazon-Kinesis-Data-Streams_light-bg.svg",
  "Analytics/AWS-Glue_light-bg.svg",
  "Analytics/Amazon-EMR_EMR-engine-MapR-M7_light-bg.svg",
  "Analytics/Amazon-EMR_HDFS-cluster_light-bg.svg",
  "Analytics/Amazon-Elasticsearch-Service_light-bg.svg",
  "Analytics/AWS-Glue_Data-catalog_light-bg.svg",
  "Analytics/AWS-Glue_Crawlers_light-bg.svg",
  "Analytics/Amazon-EMR_EMR-engine_light-bg.svg",
  "Analytics/AWS-Data-Pipeline_light-bg.svg",
  "Analytics/Amazon-Kinesis-Data-Firehose_light-bg.svg",
  "Security, Identity, & Compliance/Amazon-Inspector_Agent_light-bg.svg",
  "Security, Identity, & Compliance/AWS-CloudHSM_light-bg.svg",
  "Security, Identity, & Compliance/AWS-Identity-and-Access-Management-IAM_Add-on_light-bg.svg",
  "Security, Identity, & Compliance/AWS-Security-Hub_light-bg.svg",
  "Security, Identity, & Compliance/AWS-Identity-and-Access-Management-IAM_Long-term-Security-Credential_light-bg.svg",
  "Security, Identity, & Compliance/Amazon-Macie_light-bg.svg",
  "Security, Identity, & Compliance/AWS-Identity-and-Access-Management-IAM_Permissions_light-bg.svg",
  "Security, Identity, & Compliance/AWS-Identity-and-Access-Management_IAM_light-bg.svg",
  "Security, Identity, & Compliance/AWS-Certificate-Authority_light-bg.svg",
  "Security, Identity, & Compliance/AWS-Identity-and-Access-Management-IAM_MFA-Token_light-bg.svg",
  "Security, Identity, & Compliance/AWS-Managed-Microsoft-AD_light-bg.svg",
  "Security, Identity, & Compliance/AD-Connector_light-bg.svg",
  "Security, Identity, & Compliance/AWS-WAF_Filtering-rule_light-bg.svg",
  "Security, Identity, & Compliance/Amazon-Detective_light-bg.svg",
  "Security, Identity, & Compliance/AWS-Identity-and-Access-Management-IAM_Access-Analyzer_light-bg.svg",
  "Security, Identity, & Compliance/AWS-Artifact_light-bg.svg",
  "Security, Identity, & Compliance/AWS-Identity-and-Access-Management-IAM_Role_light-bg.svg",
  "Security, Identity, & Compliance/Amazon-Cognito_light-bg.svg",
  "Security, Identity, & Compliance/AWS-Identity-and-Access-Management-IAM_Encrypted-Data_light-bg.svg",
  "Security, Identity, & Compliance/AWS-Certificate-Manager_light-bg.svg",
  "Security, Identity, & Compliance/Amazon-Inspector_light-bg.svg",
  "Security, Identity, & Compliance/AWS-Identity-and-Access-Management-IAM_Temporary-Security-Credential_light-bg.svg",
  "Security, Identity, & Compliance/Amazon-Cloud-Directory_light-bg.svg",
  "Security, Identity, & Compliance/Security-Hub_Finding_light-bg.svg",
  "Security, Identity, & Compliance/Simple-AD_light-bg.svg",
  "Security, Identity, & Compliance/AWS-Directory-Service_light-bg.svg",
  "Security, Identity, & Compliance/Security-Identity-and-Compliance_light-bg.svg",
  "Security, Identity, & Compliance/AWS-Resource-Access-Manager_light-bg.svg",
  "Security, Identity, & Compliance/AWS-Shield_light-bg.svg",
  "Security, Identity, & Compliance/Amazon-GuardDuty_light-bg.svg",
  "Security, Identity, & Compliance/AWS-Identity-and-Access-Management-IAM_AWS-STS_light-bg.svg",
  "Security, Identity, & Compliance/AWS-Secrets-Manager_light-bg.svg",
  "Security, Identity, & Compliance/AWS-Identity-and-Access-Management-IAM_Data-Encryption-Key_light-bg.svg",
  "Security, Identity, & Compliance/AWS-WAF_light-bg.svg",
  "Security, Identity, & Compliance/AWS-Identity-and-Access-Management-IAM_AWS-STS-Alternate_light-bg.svg",
  "Security, Identity, & Compliance/AWS-Firewall-Manager_light-bg.svg",
  "Security, Identity, & Compliance/AWS-Single-Sign-On_light-bg.svg",
  "Security, Identity, & Compliance/AWS-Shield_Shield-Advanced_light-bg.svg",
  "Security, Identity, & Compliance/AWS-Key-Management-Service_light-bg.svg",
  "Internet of Things/IoT_House_light-bg.svg",
  "Internet of Things/Amazon-FreeRTOS_light-bg.svg",
  "Internet of Things/AWS-IoT-Analytics_light-bg.svg",
  "Internet of Things/IoT_Alexa-voice-service_light-bg.svg",
  "Internet of Things/IoT_Bicycle_light-bg.svg",
  "Internet of Things/IoT_Alexa-enabled-device_light-bg.svg",
  "Internet of Things/AWS-IoT-Things-Graph_light-bg.svg",
  "Internet of Things/IoT_Policy_light-bg.svg",
  "Internet of Things/IoT_Hardware-board_light-bg.svg",
  "Internet of Things/IoT_Alexa-skill_light-bg.svg",
  "Internet of Things/IoT_Travel_light-bg.svg",
  "Internet of Things/IoT_Door-lock_light-bg.svg",
  "Internet of Things/IoT_HTTP-protocol_light-bg.svg",
  "Internet of Things/AWS-IoT-Button_light-bg.svg",
  "Internet of Things/AWS-IoT-Core_light-bg.svg",
  "Internet of Things/IoT_Sensor_light-bg.svg",
  "Internet of Things/AWS-IoT-Events_light-bg.svg",
  "Internet of Things/IoT_Servo_light-bg.svg",
  "Internet of Things/IoT-Device-Jobs_Resource_light-bg.svg",
  "Internet of Things/IoT_Reported-state_light-bg.svg",
  "Internet of Things/IoT_Lightbulb_light-bg.svg",
  "Internet of Things/AWS-IoT-Analytics_Pipeline_light-bg.svg",
  "Internet of Things/IoT_Echo_light-bg.svg",
  "Internet of Things/IoT_Police-emergency_light-bg.svg",
  "Internet of Things/AWS-IoT-SiteWise_light-bg.svg",
  "Internet of Things/IoT_Action_light-bg.svg",
  "Internet of Things/IoT_Factory_light-bg.svg",
  "Internet of Things/IoT_Simulator_light-bg.svg",
  "Internet of Things/IoT_Fire-TV_light-bg.svg",
  "Internet of Things/IoT_HTTP-2-protocol_light-bg.svg",
  "Internet of Things/IoT_Desired-state_light-bg.svg",
  "Internet of Things/IoT_Shadow_light-bg.svg",
  "Internet of Things/IoT_Fire-TV-stick_light-bg.svg",
  "Internet of Things/Internet-of-Things_light-bg.svg",
  "Internet of Things/AWS-IoT-Analytics_Notebook_light-bg.svg",
  "Internet of Things/IoT_Car_light-bg.svg",
  "Internet of Things/AWS-IoT-Device-Defender_light-bg.svg",
  "Internet of Things/IoT_Over-the-air-update_light-bg.svg",
  "Internet of Things/IoT_Topic_light-bg.svg",
  "Internet of Things/IoT_Actuator_light-bg.svg",
  "Internet of Things/IoT_Certificate-manager_light-bg.svg",
  "Internet of Things/IoT_Lambda-function_light-bg.svg",
  "Internet of Things/AWS-IoT-1-Click_light-bg.svg",
  "Internet of Things/IoT_Windfarm_light-bg.svg",
  "Internet of Things/IoT_Coffee-pot_light-bg.svg",
  "Internet of Things/IoT_Cart_light-bg.svg",
  "Internet of Things/IoT_Medical-emergency_light-bg.svg",
  "Internet of Things/AWS-IoT-Analytics_Data-Set_light-bg.svg",
  "Internet of Things/AWS-IoT-Greengrass_Connector_light-bg.svg",
  "Internet of Things/IoT_Rule_light-bg.svg",
  "Internet of Things/AWS-IoT-Analytics_Data-Store_light-bg.svg",
  "Internet of Things/IoT_MQTT-protocol_light-bg.svg",
  "Internet of Things/IoT_Utility_light-bg.svg",
  "Internet of Things/AWS-IoT-Greengrass_light-bg.svg",
  "Internet of Things/IoT_Device-gateway_light-bg.svg",
  "Internet of Things/IoT_Camera_light-bg.svg",
  "Internet of Things/IoT_Thermostat_light-bg.svg",
  "Internet of Things/IoT_Bank_light-bg.svg",
  "Internet of Things/AWS-IoT-Device-Management_light-bg.svg",
  "Internet of Things/AWS-IoT-Analytics_Channel_light-bg.svg",
  "Internet of Things/IoT_Generic_light-bg.svg",
  "Database/Amazon-RDS_PostgreSQL_instance_light-bg.svg",
  "Database/Amazon-Timestream_light-bg.svg",
  "Database/Amazon-DynamoDB_Items_light-bg.svg",
  "Database/Amazon-RDS_PIOP_light-bg.svg",
  "Database/Amazon-RDS_Amazon-RDS_instance_light-bg.svg",
  "Database/Amazon-Managed-Apache-Cassandra-Service_light-bg.svg",
  "Database/Amazon-RDS_MySQL_instance-alt_light-bg.svg",
  "Database/Amazon-RDS-on-VMware_light-bg.svg",
  "Database/Amazon-DynamoDB_DAX_light-bg.svg",
  "Database/Amazon-RDS_SQL-Server_instance-alt_light-bg.svg",
  "Database/AWS-Database-Migration-Service_light-bg.svg",
  "Database/AWS-Database-Migration-Service_Database-Migration-Workflow_light-bg.svg",
  "Database/Amazon-RDS_MariaDB_instance_light-bg.svg",
  "Database/Amazon-DynamoDB_Attributes_light-bg.svg",
  "Database/Amazon-DynamoDB_Attribute_light-bg.svg",
  "Database/Amazon-Redshift_Dense-Storage-Node_light-bg.svg",
  "Database/Amazon-RDS_Amazon-RDS_instance-alt_light-bg.svg",
  "Database/Amazon-RDS_SQL-Server_instance_light-bg.svg",
  "Database/Amazon-ElastiCache_For-Memcached_light-bg.svg",
  "Database/Amazon-Neptune_light-bg.svg",
  "Database/Amazon-DocumentDB-with-MongoDB-compatibility_light-bg.svg",
  "Database/Amazon-RDS_MySQL_instance_light-bg.svg",
  "Database/Amazon-ElastiCache_For-Redis_light-bg.svg",
  "Database/Amazon-RDS_PIOPS_light-bg.svg",
  "Database/Amazon-ElastiCache_light-bg.svg",
  "Database/Amazon-DynamoDB_light-bg.svg",
  "Database/Amazon-Redshift_light-bg.svg",
  "Database/Amazon-Quantum-Ledger-Database_QLDB_light-bg.svg",
  "Database/Amazon-RDS_Oracle_instance-alt_light-bg.svg",
  "Database/Amazon-RDS_Amazon-Aurora_instance_light-bg.svg",
  "Database/Amazon-DynamoDB_Global-Secondary-Index_light-bg.svg",
  "Database/Amazon-Aurora_light-bg.svg",
  "Database/Database_light-bg.svg",
  "Database/Amazon-RDS_PostgreSQL_instance-alt_light-bg.svg",
  "Database/Amazon-RDS_MariaDB_instance-alt_light-bg.svg",
  "Database/Amazon-Redshift_Dense-Compute-Node_light-bg.svg",
  "Database/Amazon-DynamoDB_Item_light-bg.svg",
  "Database/Amazon-DynamoDB_Table_light-bg.svg",
  "Database/Amazon-ElastiCache_Cache-Node_light-bg.svg",
  "Database/Amazon-RDS_Amazon-Aurora_instance-alt_light-bg.svg",
  "Database/Amazon-RDS_Oracle_instance_light-bg.svg",
  "Database/Amazon-RDS_light-bg.svg",
  "Customer Enablement/AWS-Support_light-bg.svg",
  "Customer Enablement/Customer-Enablement_light-bg.svg",
  "Customer Enablement/AWS-Managed-Services_light-bg.svg",
  "Customer Enablement/AWS-IQ_light-bg.svg",
  "Customer Enablement/AWS-Professional-Services_light-bg.svg",
  "Machine Learning/AWS-DeepComposer_light-bg.svg",
  "Machine Learning/Amazon-Comprehend_light-bg.svg",
  "Machine Learning/Amazon-Forecast_light-bg.svg",
  "Machine Learning/AWS-Deep-Learning-AMIs_light-bg.svg",
  "Machine Learning/Amazon-SageMaker_light-bg.svg",
  "Machine Learning/Amazon-Augmented-AI_light-bg.svg",
  "Machine Learning/Amazon-Personalize_light-bg.svg",
  "Machine Learning/Amazon-Translate_light-bg.svg",
  "Machine Learning/Amazon-Textract_light-bg.svg",
  "Machine Learning/Amazon-Lex_light-bg.svg",
  "Machine Learning/Machine-Learning_light-bg.svg",
  "Machine Learning/Amazon-Transcribe_light-bg.svg",
  "Machine Learning/Amazon-SageMaker-Ground-Truth_light-bg.svg",
  "Machine Learning/AWS-DeepLens_light-bg.svg",
  "Machine Learning/Amazon-Rekognition_light-bg.svg",
  "Machine Learning/Amazon-Rekognition_Image_light-bg.svg",
  "Machine Learning/Amazon-Elastic-Inference_light-bg.svg",
  "Machine Learning/Amazon-SageMaker_Model_light-bg.svg",
  "Machine Learning/Amazon-Rekognition_Video_light-bg.svg",
  "Machine Learning/Amazon-SageMaker_Notebook_light-bg.svg",
  "Machine Learning/Amazon-SageMaker_Train_light-bg.svg",
  "Machine Learning/Apache-MXNet-on-AWS_light-bg.svg",
  "Machine Learning/Amazon-Polly_light-bg.svg",
  "Machine Learning/AWS-DeepRacer_light-bg.svg",
  "Machine Learning/AWS-Deep-Learning-Containers_light-bg.svg",
  "Machine Learning/Amazon-Fraud-Detector_light-bg.svg",
  "Machine Learning/Amazon-CodeGuru_light-bg.svg",
  "Machine Learning/Amazon-Kendra_light-bg.svg",
  "Machine Learning/TensorFlow-on-AWS_light-bg.svg",
  "Blockchain/Blockchain_Resource-Icon_light-bg.svg",
  "Blockchain/Blockchain_light-bg.svg",
  "Blockchain/Amazon-Managed-Blockchain_light-bg.svg",
  "Blockchain/Amazon-Quantum-Ledger-Database-QLDB_light-bg.svg",
  "Business Applications/Business-Applications_light-bg.svg",
  "Business Applications/Alexa-For-Business_light-bg.svg",
  "Business Applications/Amazon-Chime_light-bg.svg",
  "Business Applications/Amazon-WorkMail_light-bg.svg",
  "Developer Tools/Developer-Tools_light-bg.svg",
  "Developer Tools/AWS-CodeBuild_light-bg.svg",
  "Developer Tools/Amazon-DynamoDB_DAX_light-bg.svg",
  "Developer Tools/AWS-Tools-And-SDKs_light-bg.svg",
  "Developer Tools/AWS-X-Ray_light-bg.svg",
  "Developer Tools/AWS-CodeStar_light-bg.svg",
  "Developer Tools/AWS-Cloud9_light-bg.svg",
  "Developer Tools/AWS-CodeDeploy_light-bg.svg",
  "Developer Tools/Cloud9_Resource_light-bg.svg",
  "Developer Tools/AWS-CodeCommit_light-bg.svg",
  "Developer Tools/AWS-CodePipeline_light-bg.svg",
  "Developer Tools/AWS-Command-Line-Interface_light-bg.svg",
  "Developer Tools/AWS-Cloud-Development-Kit_light-bg.svg",
  "Media Services/Amazon-Kinesis-Video-Streams_light-bg.svg",
  "Media Services/AWS-Elemental-MediaLive_light-bg.svg",
  "Media Services/AWS-Elemental-Server_light-bg.svg",
  "Media Services/AWS-Elemental-MediaTailor_light-bg.svg",
  "Media Services/Media-Services_light-bg.svg",
  "Media Services/AWS-Elemental-MediaStore_light-bg.svg",
  "Media Services/AWS-Elemental-Delta_light-bg.svg",
  "Media Services/AWS-Elemental-Live_light-bg.svg",
  "Media Services/AWS-Elemental-Conductor_light-bg.svg",
  "Media Services/AWS-Elemental-MediaPackage_light-bg.svg",
  "Media Services/Amazon-Elastic-Transcoder_light-bg.svg",
  "Media Services/AWS-Elemental-MediaConnect_light-bg.svg",
  "Robotics/Robotics_light-bg.svg",
  "Robotics/AWS-RoboMaker_light-bg.svg",
  "Robotics/AWS-RoboMaker_Simulation_light-bg.svg",
  "Robotics/AWS-RoboMaker_Fleet-Management_light-bg.svg",
  "Robotics/AWS-RoboMaker_Development-Environment_light-bg.svg",
  "Robotics/AWS-RoboMaker_Cloud-Extension-ROS_light-bg.svg",
  "Satellite/AWS-Ground-Station_light-bg.svg",
  "Satellite/Satellite_light-bg.svg",
  "AWS Cost Management/AWS-Budgets_light-bg.svg",
  "AWS Cost Management/AWS-Cost-Explorer_light-bg.svg",
  "AWS Cost Management/AWS-Cost-Management_light-bg.svg",
  "AWS Cost Management/Reserved-Instance-Reporting_light-bg.svg",
  "AWS Cost Management/AWS-Cost-and-Usage-Report_light-bg.svg",
  "AWS Cost Management/Savings-Plans_light-bg.svg",
  "Quantum Technologies/Quantum-Technologies_light-bg.svg",
  "Quantum Technologies/AWS-Braket_light-bg.svg",
  "Storage/Amazon-FSx_light-bg.svg",
  "Storage/Amazon-Simple-Storage-Service-S3_Object_light-bg.svg",
  "Storage/Amazon-Elastic-File-System_EFS_File-system_light-bg.svg",
  "Storage/Amazon-Elastic-Block-Store-EBS_light-bg.svg",
  "Storage/AWS-Snowball_light-bg.svg",
  "Storage/Multiple-volumes_Resource-Icon_light-bg.svg",
  "Storage/Amazon-Elastic-Block-Store-EBS_Snapshot_light-bg.svg",
  "Storage/AWS-Storage-Gateway_Cached-Volume_light-bg.svg",
  "Storage/EFS-InfrequentAccess_light-bg.svg",
  "Storage/Amazon-S3-Glacier_light-bg.svg",
  "Storage/AWS-Storage-Gateway_Volume-Gateway_light-bg.svg",
  "Storage/EFS-Standard_light-bg.svg",
  "Storage/Amazon-FSx-for-Lustre_light-bg.svg",
  "Storage/Storage_light-bg.svg",
  "Storage/CloudEndure-Disaster-Recovery_light-bg.svg",
  "Storage/AWS-Snowmobile_light-bg.svg",
  "Storage/Amazon-Simple-Storage-Service-S3_light-bg.svg",
  "Storage/AWS-Storage-Gateway_File-Gateway_light-bg.svg",
  "Storage/AWS-Storage-Gateway_Tape-Gateway_light-bg.svg",
  "Storage/Amazon-Elastic-File-System_EFS_light-bg.svg",
  "Storage/AWS-Storage-Gateway_light-bg.svg",
  "Storage/AWS-Backup_light-bg.svg",
  "Storage/AWS-Storage-Gateway_Virtual-Tape-Library_light-bg.svg",
  "Storage/Amazon-Elastic-Block-Store-EBS_Volume_light-bg.svg",
  "Storage/Amazon-S3-Glacier_Vault_light-bg.svg",
  "Storage/Amazon-Simple-Storage-Service-S3_Bucket-with-Objects_light-bg.svg",
  "Storage/Amazon-Simple-Storage-Service-S3_Bucket_light-bg.svg",
  "Storage/AWS-Snowball-Edge_light-bg.svg",
  "Storage/Amazon-FSx-for-Windows-File-Server_light-bg.svg",
  "Storage/AWS-Storage-Gateway_Non-Cached-Volume_light-bg.svg",
  "Storage/AWS-Snow-Family_Snowball-Import-Export_light-bg.svg",
  "Storage/Amazon-S3-Glacier_Archive_light-bg.svg",
] as const
